mysql:
  addr: "localhost:3306"  # mysql地址
  password: "lx347255"    # mysql密码
  user: "root"         # mysql用户名
  dbname: "data"    # mysql数据库名
http:
  pre-search-url: "http://127.0.0.1:5000/api/search?message="
  doc-summary-url: "http://127.0.0.1:5000/api/summary"
  api-key: "sk-df30216a78564bfd8fd4d5ab82d1dd17"
es:
  addr: "http://localhost:9200"
  index: "policy_search_engine"
cron: # 定时运行时间
  science-center: "00 10 * * *"  # 中央科技部
  education-center: "00 11 * * *"  # 中央教育部
  industryInformatization-center: "00 12 * * *"  # 中央工信部
  stateCouncil-center: "00 13 * * *"  # 中央国务院
  external-sources: "00 14 * * *"  # 外部数据源